#!/usr/bin/env node

import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { GoogleAuth, JWT } from "google-auth-library";

const ADMIN_API_BASE = "https://analyticsadmin.googleapis.com/v1beta";
const SCOPES = ["https://www.googleapis.com/auth/analytics.edit"];

const TOOL_CUSTOM_DIMENSIONS = [
  {
    parameterName: "tool_id",
    displayName: "Tool ID",
    description: "Stable identifier for the tool used on tools.make-it-tech.com.",
  },
  {
    parameterName: "tool_name",
    displayName: "Tool Name",
    description: "Display name of the tool used on tools.make-it-tech.com.",
  },
  {
    parameterName: "tool_action",
    displayName: "Tool Action",
    description: "Action taken inside a tool, such as run, success, download, or error.",
  },
  {
    parameterName: "input_type",
    displayName: "Input Type",
    description: "Input file or content type used by a tool.",
  },
  {
    parameterName: "output_type",
    displayName: "Output Type",
    description: "Output file or content type generated by a tool.",
  },
];

const TOOL_CUSTOM_METRICS = [
  {
    parameterName: "file_count",
    displayName: "File Count",
    description: "Number of files handled by a tool event.",
    measurementUnit: "STANDARD",
  },
  {
    parameterName: "input_bytes",
    displayName: "Input Bytes",
    description: "Input size in bytes handled by a tool event.",
    measurementUnit: "STANDARD",
  },
  {
    parameterName: "output_bytes",
    displayName: "Output Bytes",
    description: "Output size in bytes generated by a tool event.",
    measurementUnit: "STANDARD",
  },
  {
    parameterName: "reduction_percent",
    displayName: "Reduction Percent",
    description: "Percent reduction reported by compression tool events.",
    measurementUnit: "STANDARD",
  },
];

loadLocalEnv();

const argv = process.argv.slice(2);
const command = argv[0];
const flags = parseFlags(argv.slice(1));
let authClient;
let accessToken;

if (!command || command === "--help" || command === "-h" || flags.help || flags.h) {
  printHelp();
  process.exit(command ? 0 : 1);
}

if (command === "list-properties") {
  authClient = await getAuthClient();
  await listProperties();
} else if (command === "find-stream") {
  authClient = await getAuthClient();
  await findStream(requiredFlag(flags, "measurement-id"));
} else if (command === "ensure-tools-definitions") {
  authClient = await getAuthClient();
  await ensureToolsDefinitions(normalizePropertyId(requiredFlag(flags, "property")));
} else {
  console.error(`Unknown command: ${command}`);
  printHelp();
  process.exit(1);
}

function loadLocalEnv() {
  for (const file of [".env.local", ".env"]) {
    const path = resolve(process.cwd(), file);
    if (!existsSync(path)) continue;

    const lines = readFileSync(path, "utf8").split(/\r?\n/);
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const match = trimmed.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
      if (!match) continue;

      const [, key, rawValue] = match;
      if (process.env[key] !== undefined) continue;
      process.env[key] = rawValue.replace(/^["']|["']$/g, "");
    }
  }
}

function parseFlags(args) {
  const result = {};
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (!arg.startsWith("--")) continue;

    const [key, inlineValue] = arg.slice(2).split("=", 2);
    if (inlineValue !== undefined) {
      result[key] = inlineValue;
      continue;
    }

    const next = args[index + 1];
    if (!next || next.startsWith("--")) {
      result[key] = true;
      continue;
    }

    result[key] = next;
    index += 1;
  }
  return result;
}

function requiredFlag(flags, name) {
  const value = flags[name];
  if (typeof value === "string" && value.trim()) return value.trim();
  console.error(`Missing required flag: --${name}`);
  process.exit(1);
}

function normalizePropertyId(property) {
  return property.startsWith("properties/") ? property : `properties/${property}`;
}

async function getAuthClient() {
  accessToken = process.env.GA_ADMIN_ACCESS_TOKEN;
  if (accessToken) return null;

  const clientEmail = process.env.GA_ADMIN_CLIENT_EMAIL ?? process.env.GOOGLE_CLIENT_EMAIL;
  const privateKey = process.env.GA_ADMIN_PRIVATE_KEY ?? process.env.GOOGLE_PRIVATE_KEY;

  if (clientEmail && privateKey) {
    return new JWT({
      email: clientEmail,
      key: privateKey.replace(/\\n/g, "\n"),
      scopes: SCOPES,
    });
  }

  const auth = new GoogleAuth({ scopes: SCOPES });
  return auth.getClient();
}

async function request(path, options = {}) {
  const url = `${ADMIN_API_BASE}${path}`;
  if (accessToken) {
    const response = await fetch(url, {
      method: options.method ?? "GET",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: options.body ? JSON.stringify(options.body) : undefined,
    });
    const text = await response.text();
    const data = text ? JSON.parse(text) : {};
    if (!response.ok) {
      const message = data.error?.message ?? response.statusText;
      throw new Error(`${response.status} ${message}`);
    }
    return data;
  }

  const response = await authClient.request({
    url,
    method: options.method ?? "GET",
    data: options.body,
  });
  return response.data;
}

async function listProperties() {
  const summaries = await listAll("/accountSummaries", "accountSummaries");
  if (summaries.length === 0) {
    console.log("No GA4 account summaries were returned for this credential.");
    return;
  }

  for (const account of summaries) {
    console.log(`${account.account} ${account.displayName ?? ""}`.trim());
    for (const property of account.propertySummaries ?? []) {
      console.log(`  ${property.property} ${property.displayName ?? ""}`.trimEnd());
    }
  }
}

async function findStream(measurementId) {
  const properties = [];
  const summaries = await listAll("/accountSummaries", "accountSummaries");

  for (const account of summaries) {
    for (const property of account.propertySummaries ?? []) {
      properties.push(property.property);
    }
  }

  for (const property of properties) {
    const streams = await listAll(`/${property}/dataStreams`, "dataStreams");
    for (const stream of streams) {
      if (stream.webStreamData?.measurementId !== measurementId) continue;

      console.log(`Found ${measurementId}`);
      console.log(`property=${property}`);
      console.log(`stream=${stream.name}`);
      console.log(`displayName=${stream.displayName ?? ""}`);
      return;
    }
  }

  console.log(`No web data stream found for measurement ID ${measurementId}.`);
}

async function ensureToolsDefinitions(property) {
  const existingDimensions = await listAll(`/${property}/customDimensions`, "customDimensions");
  const existingMetrics = await listAll(`/${property}/customMetrics`, "customMetrics");

  const dimensionParams = new Set(existingDimensions.map((dimension) => dimension.parameterName));
  const metricParams = new Set(existingMetrics.map((metric) => metric.parameterName));

  for (const dimension of TOOL_CUSTOM_DIMENSIONS) {
    if (dimensionParams.has(dimension.parameterName)) {
      console.log(`dimension exists: ${dimension.parameterName}`);
      continue;
    }

    await request(`/${property}/customDimensions`, {
      method: "POST",
      body: {
        ...dimension,
        scope: "EVENT",
        disallowAdsPersonalization: true,
      },
    });
    console.log(`dimension created: ${dimension.parameterName}`);
  }

  for (const metric of TOOL_CUSTOM_METRICS) {
    if (metricParams.has(metric.parameterName)) {
      console.log(`metric exists: ${metric.parameterName}`);
      continue;
    }

    await request(`/${property}/customMetrics`, {
      method: "POST",
      body: {
        ...metric,
        scope: "EVENT",
      },
    });
    console.log(`metric created: ${metric.parameterName}`);
  }
}

async function listAll(path, collectionKey) {
  const results = [];
  let pageToken;

  do {
    const separator = path.includes("?") ? "&" : "?";
    const pagePath = pageToken
      ? `${path}${separator}pageSize=200&pageToken=${encodeURIComponent(pageToken)}`
      : `${path}${separator}pageSize=200`;
    const data = await request(pagePath);
    results.push(...(data[collectionKey] ?? []));
    pageToken = data.nextPageToken;
  } while (pageToken);

  return results;
}

function printHelp() {
  console.log(`
Usage:
  npm run ga:admin -- list-properties
  npm run ga:admin -- find-stream --measurement-id G-R9QSFM08R7
  npm run ga:admin -- ensure-tools-definitions --property 123456789

Auth:
  One-off with gcloud: set GA_ADMIN_ACCESS_TOKEN to \`gcloud auth print-access-token\`.
  Preferred: set GOOGLE_APPLICATION_CREDENTIALS to a service-account JSON path.
  Alternative: set GA_ADMIN_CLIENT_EMAIL and GA_ADMIN_PRIVATE_KEY in .env.local.

Required Google side setup:
  1. Enable Google Analytics Admin API in the Google Cloud project.
  2. Add the service-account email to the target GA4 property with Editor or Administrator access.
`.trim());
}
